### ISSUE TITLE
Introduce yourself (v2)

### ISSUE THREAD

**Issue by jdorfman** [sustainers/discussions#1]
moving [this](https://github.com/sustainers/website/issues/128) over to here...

**Comment by techtonik** [comment]
Hi. I am the [last release manager for Roundup Tracker](https://sourceforge.net/p/roundup/mailman/roundup-devel/thread/CAPkN8xKFz0y7g5bgexNbip18oeAR1eW7ykW6kEDUStEDA%2Bj3OA%40mail.gmail.com/#msg34757349) that powers https://bugs.python.org There is a lot of big lumps of work to be done on the tracker including merging [two years old GSoC project](https://www.google-melange.com/archive/gsoc/2015/orgs/python/projects/kinggreedy.html) which did not happen, because there are no people left with time, skills and knowledge to complete the task.

I don't think there is a shortage of people in open source scene willing to help project for free. But in reality they still need money. I am a freak among my friends to protect values of open source code, and I am a poor example and nobody wants to be like me - poor and nervous. So I did Roundup release for EUR 500. There was a lot of legal problems involved to get this money in my country. Legal support would cost me EUR 90 for every consultation, and EUR 500 is less than a monthly budget for someone without a home and without children. I couldn't even allow myself to pay taxes from this sum. So I am probably a criminal, because there is a record in my bank account that I got this money.

Code is only alive while it is present in the heads of its maintainers. When their neural network is rewired, projects die. This happens when a person enters big corporate environment or outsourcing business, where all processes are tuned to squeeze as much as possible for the buck of new master. I can't say that this is bad for people - at least they have to acquire a lot of new skills - but it is certainly bad for projects, because there is no way back. Passing projects further to new people may be a good way to solve this human birth-and-death problem, but that involves much more efforts into documentation, visualization (information dissemination and accessibility) than it is possible for just EUR 500 a year. It requires sustainability not only for 2+ developers (with minimal bus factor), but also for "administrative" contacts 2+ and media crew (the more the better).

Sorry for the long post. Going to US is expensive. Hope this feedback helps. Take a look at blockchain - it is worth the hype.

**Comment by maxbrito** [comment]
Hello, I'm a software collector. 

Basically archiving anything with bytes that is likely licensed as open source, proprietary or not even have a license at all that can still fit on our disks, which today counts with trillions of files. Besides archiving, I write tools for understanding software on the forensic level. This means trying to understand the licenses, the people involved and how the software itself can be improved.

Before that, I've released my software as open source, freeware or proprietary since the past two decades depending on what helps it move forward. What I've experienced is that open source is an amazing tool but not a magic bullet for everyone. Therefore I follow with great interest this topic and will certainly try to contribute so that we (as community, myself included) can change our world a bit for the better, and create the conditions for releasing more open source that is sustainable.

**Comment by ghost** [comment]
Hi, just wanted to say, very cool that someone has setup a repo to discuss issues of fundraising, project management/governance and corporate relationships. I started the https://SourceContribute.com blog to explore those issues and to kinda bridge the gap between corporations and Free/Libre Open Source.

And I have maintained a few projects (though not as well as I should be) and have seen how much work it can be, especially for projects with hundreds of issues/PRs open.

Looking forward to see what happens here!
